import { icons,imgs as images } from '../../../../../assets/imgs'

export const Data = [
  {
    id: 1,
    name: 'Lorem',
    image: images.PostBg1,
    edit: icons.Edit1,
    dlt: icons.Delete,
    msg: icons.Message,
    emptystar: icons.starempty,
    info: icons.info,
    review: 216,
    fullstar: icons.starFilled,
    location: icons.maps,
    desc: '909 berkeley Ave Treton',
  },
  {
    id: 2,
    name: 'Lorem',
    image: images.PostBg2,
    edit: icons.Edit1,
    dlt: icons.Delete,
    msg: icons.Message,
    emptystar: icons.starempty,
    info: icons.info,
    review: 216,
    fullstar: icons.starFilled,
    location: icons.maps,
    desc: '909 berkeley Ave Treton',
  },
  {
    id: 3,
    name: 'Lorem',
    image: images.PostBg1,
    edit: icons.Edit1,
    dlt: icons.Delete,
    msg: icons.Message,
    emptystar: icons.starempty,
    info: icons.info,
    review: 216,
    fullstar: icons.starFilled,
    location: icons.maps,
    desc: '909 berkeley Ave Treton',
  },
]
